/** Shared customer-facing copy — warm Jamaican–Caribbean flair, clear and complete. */

export const copy = {
  brandTag: "Jamaican Fusion, Your Way",
  streetLine: "Good food. Bold flavor. One fusion.",
  buildTitle: "Build Your Fusion Bowl",
  buildIntro:
    "Start with your size, choose your proteins, then finish with the sides you love.",
  configuration: "Build your bowl",
  oneProtein: "One Protein",
  twoProteins: "Two Proteins",
  chooseProtein: "Choose your protein",
  chooseProteins: "Choose your proteins",
  proteinHintOne: "Pick one protein. Tap a different option anytime to switch.",
  proteinHintTwo: "Pick two proteins. Tap to add or remove.",
  proteinPanelTitle: "Proteins",
  proteinPanelHintOne: "Select one protein for your bowl.",
  proteinPanelHintTwo: "Select up to two proteins for your bowl.",
  selectBase: "Choose your base",
  selectSides: "Choose your sides",
  sidesHint: "Add up to three sides, cooked fresh every day.",
  addOnsTitle: "Extras from the truck",
  addOnsHint: "Add empanadas, wings, or a cold fruit punch. For half-and-half wings, customize from the wings menu.",
  togglePanelTitle: "Make it yours",
  customizeMobile: "Customize your bowl",
  total: "Order total",
  bowlOnly: "Bowl only",
  plusExtras: "plus extras",
  addToOrder: "Add to order",
  added: "Added to your order",
  pickMoreProtein: (n: number) =>
    n === 1 ? "Choose one more protein" : `Choose ${n} more proteins`,
  pickupEta: (mins: number) => `Ready in about ${mins} minutes`,
  pickProtein: "Choose a protein",
  loadingMenu: "Loading the menu…",
  menuErrorTitle: "We could not load the menu",
  tryAgain: "Try again",
  takeout: "Takeout",
  dineIn: "Dine in",
  stationReady: "Ordering from",
  pickupAtTruck: "Pickup at the truck window",
  wingFlavorHint:
    "Pick one flavor for the whole order, or pick two flavors for half and half.",
  wingHalfLabel: (a: string, b: string) => `Half ${a} / Half ${b}`,
  dealCustomizeHint: "Choose each item in this deal — just like ordering them on their own.",
  cart: "Your cart",
  viewCart: "Review cart and pay",
  checkout: "Checkout",
  contactPay: "Your details",
  name: "Name",
  mobile: "Mobile number (for text updates and rewards)",
  orderNotes: "Order notes",
  notesPlaceholder: "Allergies, extra sauce, or special requests…",
  redeemPoints: "Redeem reward points (100 points = $5 off)",
  subtotal: "Subtotal",
  rewards: "Rewards discount",
  tax: "Estimated tax",
  payStripe: "Pay with card",
  paying: "Starting checkout…",
  emptyCart: "Your cart is empty",
  backToBuilder: "Back to build your bowl",
  receipt: "Your receipt",
  orderAgain: "Order again",
  buildAnother: "Build another bowl",
  statusLabel: "Status",
  fullMenuTitle: "More from the truck",
  fullMenuSub:
    "Signature bowls, pasta, wings, empanadas, and daily specials — all customizable.",
  makeItYours: "Make it yours",
  customizable: "Customizable",
  customize: "Customize",
  addToCart: "Add to cart",
  close: "Close",
  notes: "Notes",
  done: "Done",
  homeHeadline: "Prime Fusion",
  homeSupport:
    "Real Jamaican flavor, cooked fresh daily. Build your bowl, add a little something extra, and we will text you when it is ready for pickup.",
  homeCta: "Build your bowl",
  homeQr: "Order for pickup",
  rewardsTitle: "Prime Rewards",
  rewardsSub: "Earn one point for every dollar. Redeem 100 points for $5 off.",
  kitchenLogin: "Kitchen login",
  adminLogin: "Admin login",
  navBuild: "Build bowl",
  navMenu: "Full menu",
  navRewards: "Rewards",
  guestOrder: "Guest order",
  foodTruckLine: "Food truck and catering",
  oneProteinBowl: "One Protein Bowl",
  twoProteinBowl: "Two Proteins Bowl",
  freshDaily: "Fresh daily",
  wingsPieces: (n: number, flavor: string) =>
    `Wings (${n} pieces) · ${flavor}`,
  included: "Included",
  upgrade: "Upgrade",
  popularUpgrade: "Guest favorite",
  baseHint: "Rice and peas or fried rice come with your bowl. Upgrade the base if you want something richer.",
  upgradeRasta: "Creamy Caribbean pasta",
  upgradeMac: "Comfort classic",
  addOnPairing: "Goes great with your bowl",
} as const;
